/**
 * Generate src/data/california/outline.ts from a public-domain US states
 * GeoJSON. The result is committed so the app has no runtime data dependency.
 *
 *   node tools/gen-outline.mjs <us-states.geojson>
 */
import { readFileSync } from 'node:fs';

const g = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const ca = g.features.find((f) => f.properties.name === 'California');
if (!ca) throw new Error('California not found in the source file');
const rings = ca.geometry.type === 'Polygon' ? [ca.geometry.coordinates] : ca.geometry.coordinates;
const ring = rings.map((r) => r[0]).sort((a, b) => b.length - a.length)[0];

const pts = ring.map(([lon, lat]) => [Number(lon.toFixed(4)), Number(lat.toFixed(4))]);
const lines = [];
for (let i = 0; i < pts.length; i += 4) {
  lines.push('  ' + pts.slice(i, i + 4).map((p) => `[${p[0]}, ${p[1]}]`).join(', ') + ',');
}

process.stdout.write(`/**
 * The California state boundary, as [longitude, latitude] pairs.
 *
 * GENERATED by tools/gen-outline.mjs — do not hand-edit.
 * Source: PublicaMundi/MappingAPI us-states.json, itself derived from US Census
 * Bureau cartographic boundary files, which are in the public domain.
 *
 * Drawn as the faintest line in the palette. It is there for orientation only:
 * it tells a reader where in the state they are looking, and nothing else. The
 * grid is the subject; the coastline is the margin note.
 */

export const CALIFORNIA_OUTLINE: [number, number][] = [
${lines.join('\n')}
];
`);
